// src/models/clientModel.js

/**
 * Client data model
 * Defines the structure of client data in the application
 */
export const clientModel = {
    id: "", // Auto-generated by Firebase
    clientCode: "", // Unique identifier with name prefix (e.g., "ACME001")
    name: "", // Client name
    contactPerson: "",
    email: "",
    phone: "",
    address: {
      line1: "",
      line2: "",
      city: "",
      state: "",
      postalCode: "",
      country: ""
    },
    gstin: "", // GST identification number
    category: "", // Regular, Premium, etc.
    
    // Estimate tracking
    estimates: {
      count: 0, // Total number of distinct estimates
      summary: [
        // Limited array of most recent estimates (e.g., 10)
        {
          estimateId: "",
          estimateNumber: "",
          projectName: "",
          currentVersion: 0,
          status: "" // Draft, Sent, Approved, etc.
        }
      ]
    }
  };
  
  /**
   * Create a new empty client with default values
   * @returns {Object} Empty client object
   */
  export const createEmptyClient = () => {
    return {
      id: "",
      clientCode: "",
      name: "",
      contactPerson: "",
      email: "",
      phone: "",
      address: {
        line1: "",
        line2: "",
        city: "",
        state: "",
        postalCode: "",
        country: ""
      },
      gstin: "",
      category: "Regular",
      estimates: {
        count: 0,
        summary: []
      }
    };
  };
  
  /**
   * Validate client data
   * @param {Object} clientData - Client data to validate
   * @returns {Object} Validation result {isValid, errors}
   */
  export const validateClient = (clientData) => {
    const errors = {};
    
    // Required fields
    if (!clientData.name) errors.name = "Client name is required";
    
    // Email validation
    if (clientData.email && !clientData.email.match(/^[^\s@]+@[^\s@]+\.[^\s@]+$/)) {
      errors.email = "Invalid email format";
    }
    
    // Phone validation - allow only numbers, spaces, and common separators
    if (clientData.phone && !clientData.phone.match(/^[0-9\s\-\+\(\)]+$/)) {
      errors.phone = "Invalid phone number format";
    }
    
    // GSTIN validation (Indian GST number format)
    if (clientData.gstin && !clientData.gstin.match(/^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z]{1}[1-9A-Z]{1}Z[0-9A-Z]{1}$/)) {
      errors.gstin = "Invalid GSTIN format";
    }
    
    return {
      isValid: Object.keys(errors).length === 0,
      errors
    };
  };