// src/models/estimateModel.js
import { ESTIMATE_STATUS } from '../constants/statusConstants';

/**
 * Enhanced estimate model with version control
 */
export const estimateModel = {
  id: "", // Auto-generated by Firebase
  estimateNumber: "", // Unique identifier (e.g., "EST-ACME001-CARD-25-0001")
  
  // Client information
  clientId: "", // Reference to client document
  clientCode: "", // Client code for easy reference
  clientName: "", // For searching and display
  
  // Version control
  version: 1, // Version number - starts at 1
  isLatestVersion: true, // Flag to indicate if this is the current version
  baseEstimateId: "", // ID of the first version (blank if this is the first)
  
  // Version history
  versionHistory: [
    {
      version: 1,
      createdBy: "", // User ID
      changeNotes: "" // Description of changes in this version
    }
    // Additional version entries will be added as revisions are made
  ],
  
  // Core project info
  projectName: "",
  date: null, // Date
  deliveryDate: null, // Date
  
  // Job details
  jobDetails: {
    jobType: "",
    quantity: 0,
    paperProvided: "",
    paperName: ""
  },
  
  // Die details
  dieDetails: {
    dieSelection: "",
    dieCode: "",
    dieSize: { length: 0, breadth: 0 },
    image: ""
  },
  
  // Process details
  lpDetails: {
    isLPUsed: false,
    noOfColors: 0,
    colorDetails: []
  },
  
  fsDetails: {
    isFSUsed: false,
    fsType: "",
    foilDetails: []
  },
  
  embDetails: {
    isEMBUsed: false,
    plateSizeType: "",
    plateDimensions: { length: 0, breadth: 0 },
    plateTypeMale: "",
    plateTypeFemale: "",
    embMR: ""
  },
  
  digiDetails: {
    isDigiUsed: false,
    digiDie: "",
    digiDimensions: { length: 0, breadth: 0 }
  },
  
  dieCutting: {
    isDieCuttingUsed: false,
    difficulty: "",
    pdc: "",
    dcMR: ""
  },
  
  sandwich: {
    isSandwichComponentUsed: false,
    lpDetailsSandwich: {
      isLPUsed: false,
      noOfColors: 0,
      colorDetails: []
    },
    fsDetailsSandwich: {
      isFSUsed: false,
      fsType: "",
      foilDetails: []
    },
    embDetailsSandwich: {
      isEMBUsed: false,
      plateSizeType: "",
      plateDimensions: { length: 0, breadth: 0 },
      plateTypeMale: "",
      plateTypeFemale: "",
      embMR: ""
    }
  },
  
  pasting: {
    isPastingUsed: false,
    pastingType: ""
  },
  
  // Calculation results
  calculations: {},
  
  // Status tracking
  status: ESTIMATE_STATUS.DRAFT
};

/**
 * Create a new estimate from a form state
 * @param {Object} formState - Current form state
 * @param {Object} clientData - Selected client data
 * @param {String} userId - Current user ID
 * @param {String} estimateNumber - Generated estimate number
 * @returns {Object} New estimate object
 */
export const createEstimateFromForm = (formState, clientData, userId, estimateNumber) => {
  return {
    estimateNumber: estimateNumber,
    
    // Client information
    clientId: clientData.id,
    clientCode: clientData.clientCode,
    clientName: clientData.name,
    
    // Version control
    version: 1,
    isLatestVersion: true,
    baseEstimateId: "",
    
    // Version history
    versionHistory: [
      {
        version: 1,
        createdBy: userId,
        changeNotes: "Initial creation"
      }
    ],
    
    // Core project info from form
    projectName: formState.orderAndPaper.projectName,
    date: formState.orderAndPaper.date,
    deliveryDate: formState.orderAndPaper.deliveryDate,
    
    // Job details from form
    jobDetails: {
      jobType: formState.orderAndPaper.jobType,
      quantity: formState.orderAndPaper.quantity,
      paperProvided: formState.orderAndPaper.paperProvided,
      paperName: formState.orderAndPaper.paperName
    },
    
    // Die details from form
    dieDetails: {
      dieSelection: formState.orderAndPaper.dieSelection,
      dieCode: formState.orderAndPaper.dieCode,
      dieSize: formState.orderAndPaper.dieSize,
      image: formState.orderAndPaper.image
    },
    
    // Copy all other process details from form
    lpDetails: { ...formState.lpDetails },
    fsDetails: { ...formState.fsDetails },
    embDetails: { ...formState.embDetails },
    digiDetails: { ...formState.digiDetails },
    dieCutting: { ...formState.dieCutting },
    sandwich: { ...formState.sandwich },
    pasting: { ...formState.pasting },
    
    // Calculation results
    calculations: formState.calculations || {},
    
    // Status
    status: ESTIMATE_STATUS.DRAFT
  };
};

/**
 * Create a new version of an existing estimate
 * @param {Object} existingEstimate - The current estimate
 * @param {Object} formState - The updated form state
 * @param {String} userId - Current user ID
 * @param {String} changeNotes - Notes about what changed
 * @returns {Object} New estimate version
 */
export const createNewVersion = (existingEstimate, formState, userId, changeNotes) => {
  const newVersion = existingEstimate.version + 1;
  
  return {
    // Keep the same estimate number and client info
    estimateNumber: existingEstimate.estimateNumber,
    clientId: existingEstimate.clientId,
    clientCode: existingEstimate.clientCode,
    clientName: existingEstimate.clientName,
    
    // Update version control
    version: newVersion,
    isLatestVersion: true,
    baseEstimateId: existingEstimate.baseEstimateId || existingEstimate.id,
    
    // Add to version history
    versionHistory: [
      ...existingEstimate.versionHistory,
      {
        version: newVersion,
        createdBy: userId,
        changeNotes: changeNotes || "Updated estimate"
      }
    ],
    
    // Updated project info from form
    projectName: formState.orderAndPaper.projectName,
    date: formState.orderAndPaper.date,
    deliveryDate: formState.orderAndPaper.deliveryDate,
    
    // Updated job details from form
    jobDetails: {
      jobType: formState.orderAndPaper.jobType,
      quantity: formState.orderAndPaper.quantity,
      paperProvided: formState.orderAndPaper.paperProvided,
      paperName: formState.orderAndPaper.paperName
    },
    
    // Updated die details from form
    dieDetails: {
      dieSelection: formState.orderAndPaper.dieSelection,
      dieCode: formState.orderAndPaper.dieCode,
      dieSize: formState.orderAndPaper.dieSize,
      image: formState.orderAndPaper.image
    },
    
    // Copy all other updated process details from form
    lpDetails: { ...formState.lpDetails },
    fsDetails: { ...formState.fsDetails },
    embDetails: { ...formState.embDetails },
    digiDetails: { ...formState.digiDetails },
    dieCutting: { ...formState.dieCutting },
    sandwich: { ...formState.sandwich },
    pasting: { ...formState.pasting },
    
    // Updated calculation results
    calculations: formState.calculations || {},
    
    // Status (typically reset to Draft for new versions)
    status: ESTIMATE_STATUS.DRAFT
  };
};